<div>
<img src=https://www.institutedata.com/wp-content/uploads/2019/10/iod_h_tp_primary_c.svg width="300">
</div>

# Lab 2.1.1 
# *Data Wrangling and Munging with Pandas*

## Part 1: Wrangling Data

The term "data wrangling" is analogous to capturing wild horses and getting them into a fenced area; the horses are data and the fencing is your computer. The more common data wrangling tasks include:

- reading flat files
- reading Excel files
- downloading from web pages
  - csv
  - html
  - json

In [3]:
import numpy as np
import pandas as pd

*It is good practice to display the library version numbers for future reference:*

In [4]:
print('Numpy: ', np.__version__)
print('Pandas: ', pd.__version__)

Numpy:  1.21.5
Pandas:  1.4.2


### CSV Files

Below are three attempts to load the file "bikeshare.csv" into a DataFrame named `bikes`. Why are they wrong?

In [5]:
# wrong:
bikes = pd.read_table('C:/Users/jadea/Documents/IOD/02.1 - Module 02 Lab/bikeshare.csv', header = None)
print(bikes.head())
print()
# Treats the header as 1 row

# wrong:
bikes = pd.read_table('C:/Users/jadea/Documents/IOD/02.1 - Module 02 Lab/bikeshare.csv', header = 1)
print(bikes.head())
print()
#Treats the 1st row of data as header due to "1"

# wrong:
bikes = pd.read_table('C:/Users/jadea/Documents/IOD/02.1 - Module 02 Lab/bikeshare.csv', header = 0)
print(bikes.head())

                                                   0
0  instant,dteday,season,yr,mnth,hr,holiday,weekd...
1  1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,...
2  2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.8,0...
3  3,2011-01-01,1,0,1,2,0,6,0,1,0.22,0.2727,0.8,0...
4  4,2011-01-01,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,...

  1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0,3,13,16
0  2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.8,0...     
1  3,2011-01-01,1,0,1,2,0,6,0,1,0.22,0.2727,0.8,0...     
2  4,2011-01-01,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,...     
3  5,2011-01-01,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,...     
4  6,2011-01-01,1,0,1,5,0,6,0,2,0.24,0.2576,0.75,...     

  instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0  1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,...                                                                   
1  2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.8,0...                                        

?:
ANSWER: Case 1 treats headings as just another data row. Case 2 treats the 1st data row as the column header. Case 3 gets the header right (row 0), but reads each row as a single column (Nb. the other two make that same mistake). 

Load the file "bikeshare.csv" into a DataFrame named `bikes`, and confirm that it was loaded properly:

In [6]:
#ANSWER:
bikes = pd.read_table('C:/Users/jadea/Documents/IOD/02.1 - Module 02 Lab/bikeshare.csv', header = 0, sep = ',')
print(bikes.head())

   instant      dteday  season  yr  mnth  hr  holiday  weekday  workingday  \
0        1  2011-01-01       1   0     1   0        0        6           0   
1        2  2011-01-01       1   0     1   1        0        6           0   
2        3  2011-01-01       1   0     1   2        0        6           0   
3        4  2011-01-01       1   0     1   3        0        6           0   
4        5  2011-01-01       1   0     1   4        0        6           0   

   weathersit  temp   atemp   hum  windspeed  casual  registered  cnt  
0           1  0.24  0.2879  0.81        0.0       3          13   16  
1           1  0.22  0.2727  0.80        0.0       8          32   40  
2           1  0.22  0.2727  0.80        0.0       5          27   32  
3           1  0.24  0.2879  0.75        0.0       3          10   13  
4           1  0.24  0.2879  0.75        0.0       0           1    1  


Note that we could have used `read.csv()` above. When is `read_table()` necessary?

?:
ANSWER: When `sep` is not the comma character, or we need fine control that `read.csv()` does not provide.

Flat files can be full of surprises. Here are some issues to watch out for:

- separator character is something other than the comma
  - ";", "|", and tab are popular
- newline character is something other than what the O/S expects 
  - Tip: Don't hard-code the character codes for carriage returns, linefeeds, etc. Use Python's built-in representation instead (e.g. Python translates "\n" to the newline character and "\t" to the tab character on any O/S).
- truncated lines
  - if there are empty fields at the end of a line it is possible that their separators will be missing, resulting in a "jagged" file
- embedded commas or quotes
  - a free-text field containing embedded commas may split into separate fields on input
  - a free-text field containing embedded quotes may not parse correctly
- unescaped characters
  - the "\" character indicates a control code to Python, which will break the I/O
    - e.g. the substring "\u0123" will be interpreted as Unicode(0123) -- which may not be what the file creator intended
  - these may need to be fixed by loading whole strings and then parsing into a new data frame
  
Tip: Most issues can be delth with by correctly specifying the parameters of the function you use to load the file. Read the doco before reading the data!

### Reading Excel Files

In [6]:
from pandas import ExcelFile  # Nb. Need to install xlrd from conda (it does not automatically install with pandas)

In [7]:
df = pd.read_excel('C:/Users/jadea/Documents/IOD/02.1 - Module 02 Lab/Iris.xls', sheet_name = 'Data')
print(df)

     Species_No  Petal_width  Petal_length  Sepal_width  Sepal_length  \
0             1          0.2           1.4          3.5           5.1   
1             1          0.2           1.4          3.0           4.9   
2             1          0.2           1.3          3.2           4.7   
3             1          0.2           1.5          3.1           4.6   
4             1          0.2           1.4          3.6           5.0   
..          ...          ...           ...          ...           ...   
145           3          2.3           5.2          3.0           6.7   
146           3          1.9           5.0          2.5           6.3   
147           3          2.0           5.2          3.0           6.5   
148           3          2.3           5.4          3.4           6.2   
149           3          1.8           5.1          3.0           5.9   

    Species_name  
0         Setosa  
1         Setosa  
2         Setosa  
3         Setosa  
4         Setosa  
..       

So, this file appears to have an embedded table of aggregates on the same sheet as the raw data (a naughty but common practice amongst analysts).

It is usually better to load data correctly than to meddle with the source file or load it 'warts and all' and then try to parse it in code. The Pandas functions for reading files have parameters that provide the control we need. For ecxample, we could make multiple calls to `read_excel()`, using combinations of the `header`, `usecols`, `skiprows`, `nrows`, and `skipfooter` parameters to load one table at a time from a spreadsheet with multiple tables.

Load the above file without the unwanted columns:

In [8]:
#ANSWER
df = pd.read_excel('C:/Users/jadea/Documents/IOD/02.1 - Module 02 Lab/Iris.xls', sheet_name = 'Data', usecols = [ 0, 1, 2, 3, 4])
print(df)

     Species_No  Petal_width  Petal_length  Sepal_width  Sepal_length
0             1          0.2           1.4          3.5           5.1
1             1          0.2           1.4          3.0           4.9
2             1          0.2           1.3          3.2           4.7
3             1          0.2           1.5          3.1           4.6
4             1          0.2           1.4          3.6           5.0
..          ...          ...           ...          ...           ...
145           3          2.3           5.2          3.0           6.7
146           3          1.9           5.0          2.5           6.3
147           3          2.0           5.2          3.0           6.5
148           3          2.3           5.4          3.4           6.2
149           3          1.8           5.1          3.0           5.9

[150 rows x 5 columns]


### Importing Data Directly from the Web

We usually want to store a local copy of a data file that we download from the Web, but when data retention is not a priority it is convenient to download the data directly into our running Python environment.

#### Importing Text Files from the Web

The web is the 'wild west' of data formats. However, we can usually expect good behaviour from files that are automatically generated by a service, such as the earthquake report:

In [8]:
df = pd.read_csv('https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/2.5_hour.csv')
df.head()

Empty DataFrame
Columns: [time, latitude, longitude, depth, mag, magType, nst, gap, dmin, rms, net, id, updated, place, type, horizontalError, depthError, magError, magNst, status, locationSource, magSource]
Index: []

[0 rows x 22 columns]

#### Importing HTML Files from the Web

Working with unstructured HTML files relies heavily on library functions. This one, however, is well-structured:

In [9]:
url = 'https://www.ccra.com/airport-codes/'

df = pd.read_html(url)
print(df)

[                City      Country Code
0            Aalborg      Denmark  AAL
1           Aalesund       Norway  AES
2             Aarhus      Denmark  AAR
3     Abbotsford, BC       Canada  YXX
4     Abbotsford, BC       Canada  YXX
...              ...          ...  ...
1574        Zanzibar     Tanzania  ZNZ
1575        Zaragoza        Spain  ZAZ
1576       Zhengzhou        China  CGO
1577        Zhoushan        China  HSN
1578          Zurich  Switzerland  ZRH

[1579 rows x 3 columns]]


In [10]:
df[0]

City      Country Code
0            Aalborg      Denmark  AAL
1           Aalesund       Norway  AES
2             Aarhus      Denmark  AAR
3     Abbotsford, BC       Canada  YXX
4     Abbotsford, BC       Canada  YXX
...              ...          ...  ...
1574        Zanzibar     Tanzania  ZNZ
1575        Zaragoza        Spain  ZAZ
1576       Zhengzhou        China  CGO
1577        Zhoushan        China  HSN
1578          Zurich  Switzerland  ZRH

[1579 rows x 3 columns]

#### Importing XML Files from the Web

XML files are semi-structured, but you're at the mercy of the file creator. If every record has the same format it will be much easier, but practical applications often require a lot of custom code. Here is an example that includes a nice parser class: http://www.austintaylor.io/lxml/python/pandas/xml/dataframe/2016/07/08/convert-xml-to-pandas-dataframe/

#### Importing JSON Files from the Web

Like XML, JSON files are semi-structured and may require work to capture the schema into a dataframe. Here is a simple example: 

In [14]:
url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/data.json'

# Load the first sheet of the JSON file into a data frame
df = pd.read_json(url, orient = 'columns')
df.head()

integer            datetime  category
0        5 2015-01-01 00:00:00         0
1        5 2015-01-01 00:00:01         0
2        9 2015-01-01 00:00:02         0
3        6 2015-01-01 00:00:03         0
4        6 2015-01-01 00:00:04         0

## Part 2: Data Munging

Data munging is manipulating data to get it into a form that we can start running analyses on (which usually means getting the data into a DataFrame). Before we get to this stage, we may need to remove headers or footers, transpose columns to rows, split wide data tables into long ones, and so on. (Nb. Excel files can be particularly troublesome, because users can format their data in mixed, complex shapes.) Essentially, we need to follow Hadley Wickham's guidelines for tidy datasets (http://vita.had.co.nz/papers/tidy-data.html):

The end goal of the cleaning data process:

- each variable should be in one column
- each observation should comprise one row
- each type of observational unit should form one table
- include key columns for linking multiple tables
- the top row contains (sensible) variable names
- in general, save data as one file per table


### Dataset Morphology

Once we have our dataset in a DataFrame (or Series, if our data is only 1-dimensional), we can start examining its size and content.

How many rows and columns are in `bikes`?

In [17]:
#ANSWER
print(bikes.shape)


(17379, 17)


What are the column names in `bikes`?

In [20]:
#ANSWER
print(bikes.columns)

Index(['instant', 'dteday', 'season', 'yr', 'mnth', 'hr', 'holiday', 'weekday',
       'workingday', 'weathersit', 'temp', 'atemp', 'hum', 'windspeed',
       'casual', 'registered', 'cnt'],
      dtype='object')


What are the data types of these columns?

In [21]:
#ANSWER
print(bikes.dtypes)

instant         int64
dteday         object
season          int64
yr              int64
mnth            int64
hr              int64
holiday         int64
weekday         int64
workingday      int64
weathersit      int64
temp          float64
atemp         float64
hum           float64
windspeed     float64
casual          int64
registered      int64
cnt             int64
dtype: object


What is the (row) index for this DataFrame?

In [22]:
#ANSWER
print(bikes.index)

RangeIndex(start=0, stop=17379, step=1)


https://www.dataquest.io/blog/python-json-tutorial/

## Slicing and Dicing

It is often preferable to refer to DataFrame columns by name, but there is more than one way to do this. 
Do `bikes['season']` and `bikes[['season']]` give the same object? Demonstrate:

In [14]:
#ANSWER
bikes[['season']].dtypes

season    int64
dtype: object

In [15]:
bikes['season'].dtypes

dtype('int64')

How would we use object notation to show the first 4 rows of `atemp`?

In [19]:
#ANSWER
print(bikes.atemp[:4])
print(bikes.atemp[:4].dtypes)#Note this method would be same data type as whatever is in the column - float64
print(bikes.loc[:4, ["atemp"]]) #Note this method would be subsetting a Dataframe and would return Object
print(bikes.loc[:4, ["atemp"]].dtypes)

0    0.2879
1    0.2727
2    0.2727
3    0.2879
Name: atemp, dtype: float64
float64
    atemp
0  0.2879
1  0.2727
2  0.2727
3  0.2879
4  0.2879
atemp    float64
dtype: object


Algorithms that loop over multiple columns often access DataFrame columns by index. However, none of the following work (try them out by uncommenting / removing the "#E: " ): 

In [26]:
bikes[[0,0]]

SyntaxError: invalid syntax (802143819.py, line 1)

What is the correct way to access the 1st row of the DataFrame by its index?

In [34]:
#ANSWER
bikes.iloc[0]

instant                1
dteday        2011-01-01
season                 1
yr                     0
mnth                   1
hr                     0
holiday                0
weekday                6
workingday             0
weathersit             1
temp                0.24
atemp             0.2879
hum                 0.81
windspeed            0.0
casual                 3
registered            13
cnt                   16
Name: 0, dtype: object

What is the correct way to access the 2nd column of the DataFrame by its index?

In [49]:
#ANSWER
bikes.iloc[:,1:4]

dteday  season  yr
0      2011-01-01       1   0
1      2011-01-01       1   0
2      2011-01-01       1   0
3      2011-01-01       1   0
4      2011-01-01       1   0
...           ...     ...  ..
17374  2012-12-31       1   1
17375  2012-12-31       1   1
17376  2012-12-31       1   1
17377  2012-12-31       1   1
17378  2012-12-31       1   1

[17379 rows x 3 columns]

## Handling Missing Values

What is the Pandas `isnull` function for? 

?
ANSWER:

We can apply `isnull` to the `bikes` DataFrame to show the result for every element:

In [35]:
bikes.isnull().head()

instant  dteday  season     yr   mnth     hr  holiday  weekday  workingday  \
0    False   False   False  False  False  False    False    False       False   
1    False   False   False  False  False  False    False    False       False   
2    False   False   False  False  False  False    False    False       False   
3    False   False   False  False  False  False    False    False       False   
4    False   False   False  False  False  False    False    False       False   

   weathersit   temp  atemp    hum  windspeed  casual  registered    cnt  
0       False  False  False  False      False   False       False  False  
1       False  False  False  False      False   False       False  False  
2       False  False  False  False      False   False       False  False  
3       False  False  False  False      False   False       False  False  
4       False  False  False  False      False   False       False  False

However, we usually start at a higher level. How many nulls are in `bikes` altogether?

In [36]:
#ANSWER
bikes.isnull().sum()

instant       0
dteday        0
season        0
yr            0
mnth          0
hr            0
holiday       0
weekday       0
workingday    0
weathersit    0
temp          0
atemp         0
hum           0
windspeed     0
casual        0
registered    0
cnt           0
dtype: int64

If this result were nonzero we would next want to find out which columns contained nulls. How can this be done in one line of code?

In [37]:
#ANSWER
bikes.isnull().sum()

instant       0
dteday        0
season        0
yr            0
mnth          0
hr            0
holiday       0
weekday       0
workingday    0
weathersit    0
temp          0
atemp         0
hum           0
windspeed     0
casual        0
registered    0
cnt           0
dtype: int64

What is the Numpy object `nan` used for? (Write a descriptive answer.)

?
ANSWER: Marking a data point as invalid.

Write (and verify) a function that performs scalar division with built-in handling of the edge case (i.e. return a value instead of just trapping the error):

In [40]:
#ANSWER nan is a placeholder for inputs that is not a number
def divide(dividend, divisor):
    if divisor == 0:
        quotient = np.nan
    else:
        quotient = dividend / divisor
    return (quotient)

print(divide(1, 5))
print(divide(1, 0))

0.2
nan


Apply the Pandas `isna` function to the following data objects:

In [41]:
x = 2.3
y = np.nan
print(x, y)

2.3 nan


In [58]:
#ANSWER
print(pd.isna(x), pd.isna(y))

False True


In [59]:
array = np.array([[1, np.nan, 3], [4, 5, np.nan]])
print(pd.isna(array))

[[False  True False]
 [False False  True]]


In [ ]:
#ANSWER
#the na_values are used for encoding values that maybe encoded differently

How is the pandas I/O parameter `na_values` used?

? ANSWER: 

## Data Profiling

### Counts

When there are categorical variables in a dataset we will want to know how many possible values there are in each column. (Nb. If the dataset is a sample of a larger one, our sample may not capture all possible values of every categorical.)

How many (different) seasons are in `bikes`?

In [43]:
#ANSWER
bikes['season'].value_counts()

3    4496
2    4409
1    4242
4    4232
Name: season, dtype: int64

In [50]:
bikes['season'].unique()

array([1, 2, 3, 4], dtype=int64)

### Ranges

Print the range of the `instant`, `dteday`, and `windspeed` columns: 

In [100]:
#ANSWER
columnnames = ['instant', 'dteday', 'windspeed']


for i in columnnames:
    print(f" Maximum {i} is {bikes[i].max()} and minimum {i} is {bikes[i].min()}")
    




 Maximum instant is 17379 and minimum instant is 1
 Maximum dteday is 2012-12-31 and minimum dteday is 2011-01-01
 Maximum windspeed is 0.8507 and minimum windspeed is 0.0


Compute and print the overall minimum and maximum of the numeric data columns:

In [60]:
bikes_min, bikes_max = (min(bikes.min(numeric_only = True)), max(bikes.max(numeric_only = True)))
bikes_min, bikes_max

(0.0, 17379.0)

In [91]:
for i in bikes.columns:

    print(f" Maximum {i} is {bikes[i].max()} and minimum {i} is {bikes[i].min()}")



 Maximum instant is 17379 and minimum instant is 1
 Maximum dteday is 2012-12-31 and minimum dteday is 2011-01-01
 Maximum season is 4 and minimum season is 1
 Maximum yr is 1 and minimum yr is 0
 Maximum mnth is 12 and minimum mnth is 1
 Maximum hr is 23 and minimum hr is 0
 Maximum holiday is 1 and minimum holiday is 0
 Maximum weekday is 6 and minimum weekday is 0
 Maximum workingday is 1 and minimum workingday is 0
 Maximum weathersit is 4 and minimum weathersit is 1
 Maximum temp is 1.0 and minimum temp is 0.02
 Maximum atemp is 1.0 and minimum atemp is 0.0
 Maximum hum is 1.0 and minimum hum is 0.0
 Maximum windspeed is 0.8507 and minimum windspeed is 0.0
 Maximum casual is 367 and minimum casual is 0
 Maximum registered is 886 and minimum registered is 0
 Maximum cnt is 977 and minimum cnt is 1


### Quantiles

Pandas makes computing quantiles easy. This is how to get the median of a Series:

In [95]:
bikes['atemp'].quantile(0.5)

0.4848

Of course, the `quantiles` method can take a tuple as its argument. Compute the 10th, 25th, 50th, 75th, and 90th percentiles in one line of code: 

In [101]:
#ANSWER
bikes['atemp'].quantile((0.1, 0.25, 0.5, 0.75, 0.9))

0.10    0.2424
0.25    0.3333
0.50    0.4848
0.75    0.6212
0.90    0.6970
Name: atemp, dtype: float64

### Cuts

Sometimes we want to split the sample not by the quantiles of the distribution but by the range of the data. Let's take a closer look at `atemp`:

In [103]:
type(bikes['atemp'])

pandas.core.series.Series

In [80]:
bikes.sample(5)

instant      dteday  season  yr  mnth  hr  holiday  weekday  \
8604      8605  2011-12-30       1   0    12   7        0        5   
10393    10394  2012-03-14       1   1     3   4        0        3   
1002      1003  2011-02-14       1   0     2  10        0        1   
2665      2666  2011-04-25       2   0     4  23        0        1   
8501      8502  2011-12-25       1   0    12  22        0        0   

       workingday  weathersit  temp   atemp   hum  windspeed  casual  \
8604            1           1  0.24  0.2576  0.75     0.0896       3   
10393           1           1  0.48  0.4697  0.67     0.0896       1   
1002            1           1  0.44  0.4394  0.33     0.2239       9   
2665            1           1  0.58  0.5455  0.78     0.2836       9   
8501            0           1  0.28  0.2727  0.61     0.1642       2   

       registered  cnt  
8604           92   95  
10393           4    5  
1002           46   55  
2665           53   62  
8501           15   17

Suppose we decide to sort these values into 4 bins of equal width, but we want to apply the resulting groups to the entire DataFrame. Basically, we need to add a row label that indcates which bin each sample belongs in. Let's call this label "atemp_level", and use the `cut` method to populate it:

In [108]:
atemp_level = pd.cut(bikes['atemp'], bins = 4)    
print(atemp_level)

0        (0.25, 0.5]
1        (0.25, 0.5]
2        (0.25, 0.5]
3        (0.25, 0.5]
4        (0.25, 0.5]
            ...     
17374    (0.25, 0.5]
17375    (0.25, 0.5]
17376    (0.25, 0.5]
17377    (0.25, 0.5]
17378    (0.25, 0.5]
Name: atemp, Length: 17379, dtype: category
Categories (4, interval[float64, right]): [(-0.001, 0.25] < (0.25, 0.5] < (0.5, 0.75] < (0.75, 1.0]]


What is `atemp_level`?

In [109]:
#ANSWER
print(type(atemp_level))
print(atemp_level.dtype)

<class 'pandas.core.series.Series'>
category


Here is a random sample of `atemp_level`:

In [111]:
atemp_level.sample(5)          

9717    mild
2790    mild
8449    mild
2408    mild
9743    mild
Name: atemp, dtype: category
Categories (4, object): ['cool' < 'mild' < 'warm' < 'hot']

So, by default, `cut` produces labels that indicate the bin boundaries for each element in the series it was applied to. Usually, we will specify labels that are appropriate to the discretisation we are applying:

In [112]:
atemp_level = pd.cut(bikes['atemp'], bins = 4, labels = ["cool", "mild", "warm", "hot"])
atemp_level.sample(5)          

9276     mild
5485      hot
12358    warm
6825     warm
4500      hot
Name: atemp, dtype: category
Categories (4, object): ['cool' < 'mild' < 'warm' < 'hot']

Incorporate the new `atemp_level` column into the `bikes` DataFrame and use it to count the number of "mild" `atemp` entries in `season` 2:

In [114]:
#ANSWER
bikes['atemp_level'] = atemp_level
bikes[(bikes.atemp_level == 'mild') & (bikes.season == 2)].atemp_level.count()

1829

*Nb. The `atemp_level` variable we created is what the R language calls a "factor". Pandas has introduced a new data type called "category" that is similar to R's factors.*

# Synthetic Data

Sometimes we may want to generate test data, or we may need to initalise a series, matrix, or data frame for input to an algorithm. Numpy has several methods we can use for this.

Execute the following, then check the shape and content of each variable:

In [115]:
# Creating arrays with initial values
a = np.zeros((3))
b = np.ones((1,3))
c = np.random.randint(1,10,(2,3,4))   # randint(low, high, size)
d = np.arange(4)
e = np.array( [[1,2,3,4], [5,6,7,8]] )

In [131]:
# Cleaning Data
arraylist = [a, b, c, d, e]

for i in arraylist:
    print(i.shape)
    print(i)
  

(3,)
[0. 0. 0.]
(1, 3)
[[1. 1. 1.]]
(2, 3, 4)
[[[5 5 1 8]
  [9 5 4 2]
  [1 8 9 7]]

 [[9 5 2 6]
  [5 6 7 1]
  [9 1 6 9]]]
(4,)
[0 1 2 3]
(2, 4)
[[1 2 3 4]
 [5 6 7 8]]


## Load Data

Load rock.csv and clean the dataset.

In [296]:
rock = pd.read_csv("C:/Users/jadea/Documents/IOD/02.1 - Module 02 Lab/rock.csv")
rock.head()

Song Clean ARTIST CLEAN Release Year  \
0        Caught Up in You  .38 Special         1982   
1            Fantasy Girl  .38 Special          NaN   
2         Hold On Loosely  .38 Special         1981   
3  Rockin' Into the Night  .38 Special         1980   
4       Art For Arts Sake         10cc         1975   

                                COMBINED  First?  Year?  PlayCount  F*G  
0        Caught Up in You by .38 Special       1      1         82   82  
1            Fantasy Girl by .38 Special       1      0          3    0  
2         Hold On Loosely by .38 Special       1      1         85   85  
3  Rockin' Into the Night by .38 Special       1      1         18   18  
4              Art For Arts Sake by 10cc       1      1          1    1

In [298]:
rock.columns


Index(['Song Clean', 'ARTIST CLEAN', 'Release Year', 'COMBINED', 'First?',
       'Year?', 'PlayCount', 'F*G'],
      dtype='object')

## Check Column Names

Check column names and clean.

In [299]:
clean_columnname = rock.columns.str.lower().str.replace('*','').str.replace('?','').str.replace(' ','_')

print(clean_columnname)

Index(['song_clean', 'artist_clean', 'release_year', 'combined', 'first',
       'year', 'playcount', 'fg'],
      dtype='object')


C:\Users\jadea\AppData\Local\Temp\ipykernel_24824\3133232426.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  clean_columnname = rock.columns.str.lower().str.replace('*','').str.replace('?','').str.replace(' ','_')
C:\Users\jadea\AppData\Local\Temp\ipykernel_24824\3133232426.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  clean_columnname = rock.columns.str.lower().str.replace('*','').str.replace('?','').str.replace(' ','_')


In [300]:
rock.columns = clean_columnname
rock.head()

song_clean artist_clean release_year  \
0        Caught Up in You  .38 Special         1982   
1            Fantasy Girl  .38 Special          NaN   
2         Hold On Loosely  .38 Special         1981   
3  Rockin' Into the Night  .38 Special         1980   
4       Art For Arts Sake         10cc         1975   

                                combined  first  year  playcount  fg  
0        Caught Up in You by .38 Special      1     1         82  82  
1            Fantasy Girl by .38 Special      1     0          3   0  
2         Hold On Loosely by .38 Special      1     1         85  85  
3  Rockin' Into the Night by .38 Special      1     1         18  18  
4              Art For Arts Sake by 10cc      1     1          1   1

## Replace Null Values With 0

Check 'release' column whether this column have any null value or not. Replace null value with 0.

In [301]:
rock['release_year'].isna().sum()

577

In [302]:
rock.release_year = rock.release_year.fillna(0)

In [303]:
rock['release_year'].isna().sum()

0

In [304]:
rock.isna().sum()

song_clean      0
artist_clean    0
release_year    0
combined        0
first           0
year            0
playcount       0
fg              0
dtype: int64

## Check Datatypes of Dataset

Check datatypes of the dataset. Is there any column which should be int instead of object? Fix the column. 

In [305]:
rock.dtypes

song_clean      object
artist_clean    object
release_year    object
combined        object
first            int64
year             int64
playcount        int64
fg               int64
dtype: object

In [306]:
rock['release_year'] = rock['release_year'].astype(int)

ValueError: invalid literal for int() with base 10: 'SONGFACTS.COM'

In [307]:
rock[rock['release_year'] == 'SONGFACTS.COM']

song_clean    artist_clean   release_year  \
1504  Bullfrog Blues  Rory Gallagher  SONGFACTS.COM   

                              combined  first  year  playcount  fg  
1504  Bullfrog Blues by Rory Gallagher      1     1          1   1

In [308]:
rock.loc[1504, 'release_year'] = 0

In [309]:
rock.loc[1504]

song_clean                        Bullfrog Blues
artist_clean                      Rory Gallagher
release_year                                   0
combined        Bullfrog Blues by Rory Gallagher
first                                          1
year                                           1
playcount                                      1
fg                                             1
Name: 1504, dtype: object

In [310]:
rock['release_year'] = pd.to_numeric(rock['release_year'])


In [311]:
rock.dtypes

song_clean      object
artist_clean    object
release_year     int64
combined        object
first            int64
year             int64
playcount        int64
fg               int64
dtype: object

In [312]:
rock.head()

song_clean artist_clean  release_year  \
0        Caught Up in You  .38 Special          1982   
1            Fantasy Girl  .38 Special             0   
2         Hold On Loosely  .38 Special          1981   
3  Rockin' Into the Night  .38 Special          1980   
4       Art For Arts Sake         10cc          1975   

                                combined  first  year  playcount  fg  
0        Caught Up in You by .38 Special      1     1         82  82  
1            Fantasy Girl by .38 Special      1     0          3   0  
2         Hold On Loosely by .38 Special      1     1         85  85  
3  Rockin' Into the Night by .38 Special      1     1         18  18  
4              Art For Arts Sake by 10cc      1     1          1   1

## Check Min, Max of Each Column

Is there any illogical value in any column? How can we fix that?

In [313]:
rock.describe().T

count         mean         std  min  25%     50%     75%  \
release_year  2230.0  1465.331390  867.196161  0.0  0.0  1973.0  1981.0   
first         2230.0     1.000000    0.000000  1.0  1.0     1.0     1.0   
year          2230.0     0.741256    0.438043  0.0  0.0     1.0     1.0   
playcount     2230.0    16.872646   25.302972  0.0  1.0     4.0    21.0   
fg            2230.0    15.048430   25.288366  0.0  0.0     3.0    18.0   

                 max  
release_year  2014.0  
first            1.0  
year             1.0  
playcount      142.0  
fg             142.0

In [314]:
rock[rock['release_year'] > 0 ].min()

song_clean                     #9 Dream
artist_clean                .38 Special
release_year                       1071
combined        #9 Dream by John Lennon
first                                 1
year                                  1
playcount                             0
fg                                    0
dtype: object

In [315]:
rock[rock['release_year']== 1071]

song_clean artist_clean  release_year             combined  first  year  \
547      Levon   Elton John          1071  Levon by Elton John      1     1   

     playcount  fg  
547          8   8

In [316]:
rock.loc[547, 'release_year'] = 0

In [317]:
rock.iloc[547]

song_clean                    Levon
artist_clean             Elton John
release_year                      0
combined        Levon by Elton John
first                             1
year                              1
playcount                         8
fg                                8
Name: 547, dtype: object

## Write Some Functions

## Write a function that will take a row of a DataFrame and print out the song, artist, and whether or not the release date is < 1970

In [285]:
def check_1970(dataframe, row):
    
    if dataframe.loc[row,'release_year'] < 1970:
        print("Release year is before 1970")
    else:
        print("Release year is on or before 1970")
    
    return dataframe.loc[row,['song_clean','artist_clean']]

In [318]:
check_1970(rock,54)

Release year is on or before 1970


song_clean      Last Child
artist_clean     Aerosmith
Name: 54, dtype: object

## Write a function that converts cells in a DataFrame to float and otherwise replaces them with np.nan

In [333]:
def convert_tofloat(column):
    column = pd.to_numeric(column,,errors='ignore')
    print(column.dtypes)
    return column
    

In [335]:
convert_tofloat(rock['song_clean'])

object


0                                  Caught Up in You
1                                      Fantasy Girl
2                                   Hold On Loosely
3                            Rockin' Into the Night
4                                 Art For Arts Sake
                           ...                     
2225                        She Loves My Automobile
2226                              Tube Snake Boogie
2227                                           Tush
2228                                     TV Dinners
2229    WAITIN' FOR THE BUS/JESUS JUST LEFT CHICAGO
Name: song_clean, Length: 2230, dtype: object

## Apply these functions to your dataset

In [340]:
rock.apply(convert_tofloat)

object
object
int64
object
int64
int64
int64
int64


song_clean artist_clean  release_year  \
0                                Caught Up in You  .38 Special          1982   
1                                    Fantasy Girl  .38 Special             0   
2                                 Hold On Loosely  .38 Special          1981   
3                          Rockin' Into the Night  .38 Special          1980   
4                               Art For Arts Sake         10cc          1975   
...                                           ...          ...           ...   
2225                      She Loves My Automobile       ZZ Top             0   
2226                            Tube Snake Boogie       ZZ Top          1981   
2227                                         Tush       ZZ Top          1975   
2228                                   TV Dinners       ZZ Top          1983   
2229  WAITIN' FOR THE BUS/JESUS JUST LEFT CHICAGO       ZZ Top          1973   

                                               combined  first  year  \
0                       Caught Up in You by .38 Special      1     1   
1                           Fantasy Girl by .38 Special      1     0   
2                        Hold On Loosely by .38 Special      1     1   
3                 Rockin' Into the Night by .38 Special      1     1   
4                             Art For Arts Sake by 10cc      1     1   
...                                                 ...    ...   ...   
2225                  She Loves My Automobile by ZZ Top      1     0   
2226                        Tube Snake Boogie by ZZ Top      1     1   
2227                                     Tush by ZZ Top      1     1   
2228                               TV Dinners by ZZ Top      1     1   
2229  WAITIN' FOR THE BUS/JESUS JUST LEFT CHICAGO by...      1     1   

      playcount   fg  
0            82   82  
1             3    0  
2            85   85  
3            18   18  
4             1    1  
...         ...  ...  
2225          1    0  
2226         32   32  
2227        109  109  
2228          1    1  
2229          2    2  

[2230 rows x 8 columns]

## Describe the new float-only DataFrame.

>




---



---



> > > > > > > > > © 2022 Institute of Data


---



---



